[tool.poetry]
name = "dataprep"
version = "0.2.4"
description = "Dataprep: Data Preparation in Python"
authors = ["SFU Database System Lab <dsl.cs.sfu@gmail.com>"]
maintainers = [
    "Weiyuan Wu <youngw@sfu.com>", 
    "Jinglin Peng <jinglin_peng@sfu.ca>",
    "Pei Wang <peiw@sfu.ca>",
    "Brandon Lockhart <brandon_lockhart@sfu.ca>",
    "Song Bian <biansonghz@gmail.com>"
]

license = "MIT"

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/sfu-db/dataprep"
homepage = "https://github.com/sfu-db/dataprep"

keywords = ["dataprep", "eda", "data connector", "data science", "exploratory data analysis", "data exploration"]

[tool.poetry.dependencies]
python = "^3.6.1"

# Dependencies for EDA
dask = { version = "~2.13", extras = [ "complete" ]}
pandas = "~1.0"
numpy = "~1.18"
scipy = "~1.4"
holoviews = "~1.13"
bokeh = "~2.0"

# Dependencies for DataConnector
jsonschema = "~3.2"
requests = "~2.23"
jinja2 = "~2.11"
jsonpath2 = "~0.4"
lxml = "~4.5"

[tool.poetry.dev-dependencies]
pylint = "~2.4"
pytest = "~5.4"
mypy = "~0.770"
black = "19.10b0"
nbsphinx = "~0.5"
sphinx = "~2.4"
toml = "^0.10.0"
rstcheck = "^3.3.1"
sphinx-autobuild = "^0.7.1"

[tool.black]
line-length = 88
target-version = ['py36', 'py37']
exclude = '''
(
    /(
        \.eggs
    | \.git
    | \.pytype
    | \.pytest_cache
    | build
    | dist
    )/
)
'''

[tool.semantic_release]
version_variable = "dataprep/__init__.py:__version__"
version_source = "tag"
commit_subject = "v{version}"
commit_message = "Bump to v{version}"
commit_author = "Weiyuan Wu <youngw@sfu.ca>"
branch = "master"
commit_version_number = true

[build-system]
requires = ["poetry>=1"]
build-backend = "poetry.masonry.api"
